apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-backend
  labels:
    app: bookstore-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-backend
  template:
    metadata:
      labels:
        app: bookstore-backend
    spec:
      containers:
        - name: bookstore-backend
          image: public.ecr.aws/h5d6x1v5/bookstore-registry:1.0.1
          ports:
            - containerPort: 5000
