apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  selector:
    app: bookstore-backend 
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5000
  type: LoadBalancer
