apiVersion: v1
kind: Service
metadata:
  name: bookstore-frontend-service
spec:
  selector:
    app: bookstore-frontend
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80
  type: LoadBalancer